CREATE TABLE IF NOT EXISTS annonces (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
entreprise_id INTEGER NOT NULL,
contact_id BIGINT,
type_annonce INTEGER,
type_contenu INTEGER,
poste VARCHAR(255),
reference VARCHAR(255),
status_annonce INTEGER,
date_envoi TIMESTAMP WITHOUT TIME ZONE,
CONSTRAINT pk_annonces PRIMARY KEY (id)
);

